[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
